import 'dart:convert';
import 'dart:io';

import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../models/cycle_entry.dart';
import '../../models/symptom.dart';
import 'cycle_repository.dart';

/// Service for exporting cycle data to a PDF file
class DataExportService {
  DataExportService({
    required CycleRepository cycleRepository,
    required dynamic transactionRepository, // kept for API compatibility
    required dynamic userRepository, // kept for API compatibility
  }) : _cycleRepository = cycleRepository;

  final CycleRepository _cycleRepository;

  static const _exportMarker = '%CHOICE_EXPORT_V1:';

  /// Export all cycle data to a PDF file and return the file path.
  ///
  /// Один \"цикл\" здесь — это все подряд идущие дни с отметкой месячных
  /// без пропусков между ними (между днями цикла нет дней без записи).
  /// Длина цикла считается от первого дня текущего цикла до первого дня следующего.
  Future<String> exportAllData() async {
    // Fetch all daily entries
    final allEntries = await _cycleRepository.fetchEntries();

    final pdf = pw.Document();
    final dateFormatter = DateFormat('dd.MM.yyyy');

    if (allEntries.isEmpty) {
      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (context) => pw.Center(
            child: pw.Text('No cycle data to export'),
          ),
        ),
      );
    } else {
      final cycles = _groupIntoCycles(allEntries);

      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          build: (context) => [
            pw.Text(
              'Cycle report',
              style: pw.TextStyle(
                fontSize: 20,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            pw.SizedBox(height: 16),
            ...cycles.map(
              (cycle) => _buildCycleSection(cycle, dateFormatter),
            ),
          ],
        ),
      );
    }

    final bytes = await pdf.save();
    final payload = jsonEncode({
      'version': 1,
      'exportedAt': DateTime.now().toIso8601String(),
      'cycleEntries': allEntries.map((e) => e.toJson()).toList(),
    });
    final payloadB64 = base64UrlEncode(utf8.encode(payload));
    // PDF readers ignore trailing bytes after %%EOF, so we can safely append our export payload.
    final exportBytes = <int>[
      ...bytes,
      ...utf8.encode('\n$_exportMarker$payloadB64\n'),
    ];

    // Get directory for saving file
    final directory = await _getExportDirectory();
    final timestamp = DateFormat('yyyy-MM-dd_HH-mm-ss').format(DateTime.now());
    final fileName = 'choice_cycles_$timestamp.pdf';
    final file = File('${directory.path}/$fileName');

    // Write PDF file
    await file.writeAsBytes(exportBytes);

    return file.path;
  }

  /// Import cycle data from a previously exported PDF.
  ///
  /// NOTE: This expects a PDF generated by this app (with an embedded export payload).
  Future<List<CycleEntry>> importFromPdfPath(String pdfPath) async {
    final file = File(pdfPath);
    final bytes = await file.readAsBytes();
    // Decode as UTF-8 with replacement to make marker search robust.
    final text = utf8.decode(bytes, allowMalformed: true);
    final markerIndex = text.lastIndexOf(_exportMarker);
    if (markerIndex < 0) return const [];

    final start = markerIndex + _exportMarker.length;
    var end = text.indexOf('\n', start);
    if (end < 0) end = text.length;
    final payloadB64 = text.substring(start, end).trim();
    if (payloadB64.isEmpty) return const [];

    final payloadJson = utf8.decode(base64Url.decode(payloadB64));
    final payload = jsonDecode(payloadJson) as Map<String, dynamic>;
    final entries = (payload['cycleEntries'] as List<dynamic>? ?? const [])
        .map((e) => CycleEntry.fromJson(e as Map<String, dynamic>))
        .toList();

    return entries;
  }

  pw.Widget _buildCycleSection(
    _ExportCycle cycle,
    DateFormat dateFormatter,
  ) {
    final startDate = dateFormatter.format(cycle.start);
    final endDate = dateFormatter.format(cycle.end);

    final symptoms = cycle.symptoms;
    final symptomLines = symptoms.map((s) {
      final label = s.type.label;
      final intensity = s.intensity.name;
      return '$label (${intensity})';
    }).toList();

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text('1) Period start date: $startDate'),
        pw.Text('2) Period end date: $endDate'),
        pw.Text('3) Symptoms:'),
        if (symptomLines.isEmpty)
          pw.Padding(
            padding: const pw.EdgeInsets.only(left: 12),
            child: pw.Text('- none'),
          )
        else
          pw.Padding(
            padding: const pw.EdgeInsets.only(left: 12),
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: symptomLines
                  .map((line) => pw.Text('- $line'))
                  .toList(),
            ),
          ),
        if (cycle.cycleLengthDays != null)
          pw.Text('4) Cycle length: ${cycle.cycleLengthDays} days')
        else
          pw.Text('4) Cycle length: —'),
        pw.SizedBox(height: 12),
      ],
    );
  }

  /// Group flat list of daily entries into logical cycles.
  List<_ExportCycle> _groupIntoCycles(List<CycleEntry> entries) {
    if (entries.isEmpty) return [];

    // Sort ascending by start date
    final sorted = List<CycleEntry>.from(entries)
      ..sort((a, b) => a.cycleStart.compareTo(b.cycleStart));

    final cyclesEntries = <List<CycleEntry>>[];
    var current = <CycleEntry>[];

    DateTime normalize(DateTime d) => DateTime(d.year, d.month, d.day);

    for (final entry in sorted) {
      if (current.isEmpty) {
        current.add(entry);
        continue;
      }
      final prev = current.last;
      final prevEnd = normalize(prev.cycleEnd);
      final entryStart = normalize(entry.cycleStart);
      final gap = entryStart.difference(prevEnd).inDays;

      // Если между днями нет пропуска (gap == 1) — тот же цикл.
      // Если есть пропуск (gap > 1) — новый цикл.
      if (gap <= 1) {
        current.add(entry);
      } else {
        cyclesEntries.add(current);
        current = [entry];
      }
    }
    if (current.isNotEmpty) {
      cyclesEntries.add(current);
    }

    // Превращаем группы дней в _ExportCycle
    final cycles = <_ExportCycle>[];
    for (var i = 0; i < cyclesEntries.length; i++) {
      final group = cyclesEntries[i];
      final start = normalize(group.first.cycleStart);
      final end = normalize(group.last.cycleEnd);

      // Собираем симптомы: по типу берём максимальную интенсивность за цикл
      final Map<SymptomType, SymptomIntensity> agg = {};
      for (final entry in group) {
        for (final s in entry.symptoms) {
          final prev = agg[s.type];
          if (prev == null || s.intensity.index > prev.index) {
            agg[s.type] = s.intensity;
          }
        }
      }
      final symptoms = agg.entries
          .map(
            (e) => SymptomLog(
              type: e.key,
              intensity: e.value,
            ),
          )
          .toList();

      // Длина цикла: от первого дня текущего до первого дня следующего цикла
      int? cycleLength;
      if (i + 1 < cyclesEntries.length) {
        final nextGroup = cyclesEntries[i + 1];
        final nextStart = normalize(nextGroup.first.cycleStart);
        cycleLength = nextStart.difference(start).inDays;
      }

      cycles.add(
        _ExportCycle(
          start: start,
          end: end,
          symptoms: symptoms,
          cycleLengthDays: cycleLength,
        ),
      );
    }

    // Отдаём в обратной хронологии (последние циклы первыми)
    cycles.sort((a, b) => b.start.compareTo(a.start));
    return cycles;
  }

  Future<Directory> _getExportDirectory() async {
    if (Platform.isAndroid) {
      // On Android, use Downloads directory
      final directory = Directory('/storage/emulated/0/Download');
      if (await directory.exists()) {
        return directory;
      }
      // Fallback to app documents directory
      return await getApplicationDocumentsDirectory();
    } else if (Platform.isIOS) {
      // On iOS, use app documents directory
      return await getApplicationDocumentsDirectory();
    } else {
      // For other platforms, use documents directory
      return await getApplicationDocumentsDirectory();
    }
  }
}

class _ExportCycle {
  _ExportCycle({
    required this.start,
    required this.end,
    required this.symptoms,
    required this.cycleLengthDays,
  });

  final DateTime start;
  final DateTime end;
  final List<SymptomLog> symptoms;
  final int? cycleLengthDays;
}

